language: java
jdk:
  - oraclejdk8
sudo: false
install: true
script: 
  cd jbot; 
  mvn clean install -Dmaven.javadoc.skip=true -B -V;
  cd ../jbot-example;
  mvn clean install -Dmaven.javadoc.skip=true -B -V;